draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  svg_extra_style: |
    /* For default sytles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */

    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held {
        fill: #ffc;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }

  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  zmk_additional_includes: ["zmk-helpers/include"]
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Your Home Row Mods
    "&HomeRowModLeft LGUI A": {t: A, h: $$mdi:apple-keyboard-command$$}
    "&HomeRowModLeft LALT S": {t: S, h: $$mdi:apple-keyboard-option$$}
    "&HomeRowModLeft LCTRL D": {t: D, h: $$mdi:apple-keyboard-control$$}
    "&HomeRowModLeft LSHFT F": {t: F, h: $$mdi:apple-keyboard-shift$$}
    "&HomeRowModRight RSHFT J": {t: J, h: $$mdi:apple-keyboard-shift$$}
    "&HomeRowModRight LCTRL K": {t: K, h: $$mdi:apple-keyboard-control$$}
    "&HomeRowModRight LALT L": {t: L, h: $$mdi:apple-keyboard-option$$}
    "&HomeRowModRight LGUI SEMI": {t: ";", h: $$mdi:apple-keyboard-command$$}
    
    # Your thumb cluster hold-taps
    "&magic_shift_hold_tap LSHFT 0": {t: Magic, h: Shift}
    "&smart_num_hold_tap NUM_LAYER 0": {t: Num TD, h: Num Lyr}
    "&lt_space_nav_layer NAV_LAYER 0": {t: Space, h: NAV}

    "&comma_morph_level1": {t: ",", s: ";"}
    "&dot_morph_level1": {t: ".", s: ":"}
    "&qmark_excl_morph": {t: "?", s: "!"}

    # Your copy/cut tap-dance
    "&copy_cut_dance": {t: Copy, h: Cut}

    # Other custom behaviors
    "&leader_main": Leader
    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word

    # Bluetooth and System keys
    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4
    "&bt BT_SEL 4": BT 5
    "&bt BT_CLR": BT Clr
    "&out OUT_TOG": Out

  zmk_keycode_map:

    C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    LCTRL: Ctrl
    LALT: Alt
    LGUI: Gui
    LSHFT: Shift
    RCTRL: Ctrl
    RALT: Alt
    RGUI: Gui
    RSHFT: Shift

    BSPC: Bspc
    DEL: Del
    ESC: Esc
    RET: Enter
    SPACE: Spc
    TAB: Tab
    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End
    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →
    
    AMPERSAND: "&"
    APOS: "'"
    ASTERISK: "*"
    AT: "@"
    BACKSLASH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    EQUAL: "="
    EXCL: "!"
    FSLH: /
    GRAVE: "`"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LPAR: (
    LT: <
    MINUS: "-"
    PIPE: "|"
    PLUS: +
    QMARK: "?"
    RBKT: "]"
    RBRC: "}"
    RPAR: )
    SEMI: ;
    SLASH: /
    SQT: "'"
    TILDE: "~"
    UNDER: _
